
<?php $__env->startSection('content'); ?>
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row bg-title">
                <div class="col-lg-12">
                    <!-- <h4 class="page-title">Welcome to My Admin</h4>
                    <ol class="breadcrumb">
                        <li><a href="#">Dashboard</a></li>
                    </ol> -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            
            
                
                    
                    
                                            
                                               
                                        
                
                
                    
                        
                            
                                
                                    
                                        
                                    
                                    
                                        
                                    
                                        

                                    
                                    
                                
                            
                            
                                
                                    
                                        
                                    
                                    
                                    
                                        
                                
                            
                        

                    
                

                
                
                
                
                
                

                
                

                

            
            
                
                    

                    
                        
                            
                                
                                
                                    
                                
                                
                            
                        
                        
                            
                                
                                
                                    
                                
                                
                            
                        
                        
                            
                                
                                
                                    
                                
                                
                            
                        
                        
                            
                                
                                
                                    
                                
                                
                            
                        
                        
                            
                                
                                
                                    
                                
                                
                            
                        
                        
                            
                                
                                
                                    
                                
                                
                            
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                    
                

                
                    
                        
                        
                               
                            
                            
                                
                                
                                
                                
                                
                                
                                
                                
                            
                            
                            
                            
                                
                                    
                                        
                                    
                                
                                    
                                        
                                            
                                            
                                            
                                            
                                                
                                                    
                                                
                                                    
                                                
                                            
                                            
                                            
                                            
                                            
                                                
                                                                               
                                                
                                            
                                                
                                                                               
                                                
                                            
                                                
                                                                               
                                                
                                            
                                        
                                    
                                
                            
                            
                            
                            
                                
                                
                                
                                
                                
                                
                                
                                
                            
                            
                        
                    
                
            
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.master', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>